# 파일 규격 버전
version: "3"
# 이 항목 밑에 실행하려는 컨테이너 들을 정의
services: 
  identity:
    # 사용할 이미지
    image: postgres
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너 이름 설정
    container_name: identity-db
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: admin
      POSTGRES_DB: identity
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5435:5432"
  postgres:
    # 사용할 이미지
    image: postgres
    # 컨테이너 실행 시 재시작
    restart: always
    # 컨테이너 이름 설정
    container_name: auction-db
    environment:
      POSTGRES_PASSWORD: 1111
      POSTGRES_USER: admin
      POSTGRES_DB: auction
    # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
    ports:
      - "5434:5432"
  pgadmin:
    container_name: auction-pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1111
    ports:
      - "5050:80"
